Added missing stop_review job for pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -125,3 +125,56 @@ deploy:
           | jq
       fi
 
+stop_review:
+  stage: teardown
+  image: $CI_REGISTRY_IMAGE/utils:latest
+  environment:
+    name: review/$CI_COMMIT_REF_NAME
+    action: stop
+  rules:
+    - if: $CI_MERGE_REQUEST_ID
+      when: manual
+  script:
+    - |
+      set -e
+
+      export PORTAINER_TOKEN=$(curl -X POST "https://portainer.doe24.swarm.chasacademy.dev/api/auth" \
+        --json '{"username": "'$PORTAINER_USER'", "password": "'$PORTAINER_PASSWORD'"}' \
+        | jq -r '.jwt')
+
+      export STACK_NAME=$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME
+      echo "STACK: $STACK_NAME"
+
+      export ENDPOINT_ID=$(curl -sSL \
+        -H "Authorization: Bearer $PORTAINER_TOKEN" \
+        https://portainer.doe24.swarm.chasacademy.dev/api/endpoints \
+        | jq -r '.[] | select(.Name == "primary") | .Id')
+
+      echo "Endpoint: $ENDPOINT_ID"
+
+      export SWARM_ID=$(curl -sSL \
+        -H "Authorization: Bearer $PORTAINER_TOKEN" \
+        https://portainer.doe24.swarm.chasacademy.dev/api/endpoints \
+        | jq -r '.[] | select(.Name == "primary") | .Snapshots[0].DockerSnapshotRaw.Info.Swarm.Cluster.ID')
+
+      echo "Swarm: $SWARM_ID"
+
+      NORMALIZED_STACK_NAME=$(echo "$STACK_NAME" | tr -cd '[:alnum:]_-')
+
+      echo "Checking if stack $NORMALIZED_STACK_NAME is present..."
+      STACK_ID=$(curl -sSL \
+        -H "Authorization: Bearer $PORTAINER_TOKEN" \
+        https://portainer.doe24.swarm.chasacademy.dev/api/stacks \
+        | jq -r --arg NAME "$NORMALIZED_STACK_NAME" '.[] | select(.Name == $NAME) | .Id')
+
+      echo "Stack id: \"$STACK_ID\""
+
+      if [ -z "$STACK_ID" ]; then
+        echo "Stack $STACK_ID $STACK_NAME not found!"
+        exit 1
+      else 
+        echo "Deleting stack $STACK_ID ($STACK_NAME)"
+        curl -X DELETE \
+          "https://portainer.doe24.swarm.chasacademy.dev/api/stacks/$STACK_ID?endpointId=$ENDPOINT_ID" \
+          -H "Authorization: Bearer $PORTAINER_TOKEN"
+      fi
